### ISSUE TITLE
[rabbit-to-slack] Create docker image

### ISSUE THREAD

**Issue by anatolek** [Kv-126-DevOps/rabbit-to-slack#3]
Please add it to public.ecr.aws/b4p0m4d6/kv126 (see https://eu-central-1.console.aws.amazon.com/ecr/repositories/public/779414916509/kv126?region=eu-central-1)

There should be 2 versions `latest` and `1.0.0`

**Comment by Olyakaya** [comment]
In the branch 3-rabbit-to-slack-create-docker-image there was added Dockerfile
